"""Closed model registry and provider-independent text generation contracts."""

from llm_runtime.registry import (
    BitsAndBytes4BitSettings,
    FourBitQuantType,
    LocalTransformersRoute,
    ModelRoute,
    ModelRouteError,
    OpenRouterRoute,
    RouteAvailability,
    TorchDTypeId,
    registered_routes,
    resolve_route,
)
from llm_runtime.types import (
    Capability,
    ChatMessage,
    GenerationError,
    GenerationFailureKind,
    GenerationSettings,
    MAX_RETRY_DELAY_SECONDS,
    MessageRole,
    ModelId,
    ProviderId,
    QuantizationId,
    RuntimeId,
    TextGenerator,
)

__all__ = [
    "Capability",
    "BitsAndBytes4BitSettings",
    "ChatMessage",
    "GenerationError",
    "GenerationFailureKind",
    "GenerationSettings",
    "FourBitQuantType",
    "MAX_RETRY_DELAY_SECONDS",
    "LocalTransformersRoute",
    "MessageRole",
    "ModelId",
    "ModelRoute",
    "ModelRouteError",
    "OpenRouterRoute",
    "ProviderId",
    "QuantizationId",
    "RouteAvailability",
    "RuntimeId",
    "TextGenerator",
    "TorchDTypeId",
    "registered_routes",
    "resolve_route",
]
